- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/entity/Entity.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/entity/User.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/enumtype/ElementalType.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/vo/Money.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/vo/VO.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/exception/Exception.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/exception/MoneyNegativeException.java
---
* #7 
---
---
* 없음
*
---
---
* 유저 엔티티 생성
* 보유금 VO 설정
* 속성 enum 설정
* 보유금 관련 Exception 처리 클래스 생성
---
---
*
---
---
* 없음
> [#7] User Entity 생성

- src/main/java/com/ohgiraffers/webrpg/database/ExampleInmemoryDatabase.java
- src/main/java/com/ohgiraffers/webrpg/database/UserInMemoryDatabase.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/entity/Entity.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/entity/User.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/enumtype/ElementalType.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/vo/Money.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/vo/VO.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/exception/Exception.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/exception/MoneyNegativeException.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/repository/Repository.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/repository/UserRepository.java
- src/main/java/com/ohgiraffers/webrpg/user/infra/repository/InMemoryUserRepository.java
- src/main/java/com/ohgiraffers/webrpg/user/infra/repository/InfraRepository.java
---
* #8 
* #9 
* #10 
---
---
* 없음
---
---
* userInMemoryDatabase 구현
* userInMemoryDatabase 엔 findUserBySequence 메소드와 findUserByName 메소드만 구현
* UserRepository 추상 인터페이스로 구현
* InMemoryUserRepository는 UserRepository를 상속받으며 해당 메소드들을 Override함
---
---
* 없음
---
---
* 없음
> [User] InMemoryDatabase, Repository interface & interface implements class 구현

- src/main/java/com/ohgiraffers/webrpg/user/application/service/ApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/user/application/service/UserApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/service/UserDomainService.java
---
* #17 
---
---
* 없음
---
---
* 유저 어플리케이션 서비스에 유저 도메인 서비스와 유저 레포지토리 클래스 의존성 주입
* 기본적인 유저 정보 응답 메소드 구현
* 추후 기능 구현에 따라 메소드 추가 필요
---
---
* 없음
---
---
> [#17] UserApplicationService 클래스 구현

- src/main/java/com/ohgiraffers/webrpg/database/Map.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/ChoiceMapController.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/Controller.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/MonsterAppearController.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/MonsterAttackController.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/UserAttackController.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/service/ApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/service/ChoiceMapApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/service/MonsterAppearApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/service/MonsterAttackApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/service/UserAttackApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/hunt/domain/service/ChoiceMapDomainService.java
- src/main/java/com/ohgiraffers/webrpg/hunt/domain/service/MonsterAppearDomainService.java
- src/main/java/com/ohgiraffers/webrpg/hunt/domain/service/MonsterAttackDomainService.java
- src/main/java/com/ohgiraffers/webrpg/hunt/domain/service/UserAttackDomainService.java
* 패키지 구조에 있어서 문제가 있는 지
---
* ApplicationService, DomainService, Controller
---
> [Hunt] 패키지 구조 설정-1

- src/main/java/com/ohgiraffers/webrpg/upgrade/application/service/ApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/application/service/UpgradeApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/RequestService.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/UpgradeDomainService.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/getResult/GetUserInfoResult.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/getResult/GetUserResult.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/getResult/GetUserUpgradeStatResult.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/pay/Pay.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/valid/Valid.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/infra/service/UserRequestService.java
- src/main/resources/application.properties
---
* #37 
---
---
* 없음
---
---
* RequestService를 추상화 인터페이스로 사용
* Upgrade Package 영역에서 UserApplicationService에 강한 의존성을 가지는 건 UserRequestService 클래스 하나
* GetResult 패키지 안에  UserApplicationService 메소드 응답을 위한 클래스를 정의하여 데이터에 대한 의존성을 좀 더 낮춤.
* @madirony @ahnichan @pyunghun 사냥 패키지에서도 이러한 형태로 의존성을 주입하면 될 것
---
---
* 없음
---
---
* 없음
> [#37] 강화 Service 에 유저 ApplicationService 의존성 주입

- src/main/java/com/ohgiraffers/webrpg/user/application/dto/UserStatDTO.java
- src/main/java/com/ohgiraffers/webrpg/user/application/service/UserApplicationService.java
> [#41] UserStatDTO 필드 추가

- settings.gradle
- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/UserAttackController.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/dto/MonsterUseDTO.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/dto/UserAttackDTO.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/service/UserAttackApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/hunt/domain/service/UserAttackDomainService.java
---
* UserAttackController  50번째 줄 오류의 이유를 잘 모르겠다.
* 작성한 이유는 몬스터의 체력 - 유저의 total 공격력을 빼려고 의도함.
---
* Controller, Service 등등에서 사용하고 있는 기능들이 잘 맞는지
* User 쪽에서 가져오는 정보들을 알맞게 가져오고 있는 건지
--- 
*
---
---
*
---
---
> [Hunt] 컨트롤러, 어플리케이션 서비스 , 도메인 서비스 살짝 구현

- src/main/java/com/ohgiraffers/webrpg/database/UserInMemoryDatabase.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/application/dto/UpgradeResultDTO.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/application/service/UpgradeApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/aggregate/enumtype/FlagEnum.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/RequestService.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/UpgradeDomainService.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/getResult/GetUserInfoResult.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/getResult/GetUserUpgradeStatusResult.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/infra/service/UserRequestService.java
- src/main/java/com/ohgiraffers/webrpg/user/application/dto/UserInfoDTO.java
- src/main/java/com/ohgiraffers/webrpg/user/application/service/UserApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/repository/UserRepository.java
- src/main/java/com/ohgiraffers/webrpg/user/infra/repository/InMemoryUserRepository.java
- src/test/java/com/ohgiraffers/webrpg/user/application/service/UserApplicationServiceTests.java
---
* #43 
---
---
* 없음
---
---
* 강화 어플리케이션 서비스 구현 완료 
* 해당 클래스의 메소드를 강화 컨트롤러에서 사용하면 됩니다.
---
---
* 없음
---
---
* 추후 테스트 예정
> [#43] Upgrade Application Service 구현

- src/main/java/com/ohgiraffers/webrpg/database/UserInMemoryDatabase.java
- src/main/java/com/ohgiraffers/webrpg/user/application/service/UserApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/repository/UserRepository.java
- src/main/java/com/ohgiraffers/webrpg/user/infra/repository/InMemoryUserRepository.java
---
* #48 
---
---
* 없음
---
---
* 없음
---
---
* 없음
---
---
* 없음
> [#48] Upgrade Application Service 구현

- settings.gradle
- src/main/java/com/ohgiraffers/webrpg/user/application/controller/Controller.java
- src/main/java/com/ohgiraffers/webrpg/user/application/controller/UserController.java
- src/main/java/com/ohgiraffers/webrpg/user/application/controller/userApplication.java
- src/main/java/com/ohgiraffers/webrpg/user/application/dto/UserInfoDTO.java
- src/main/java/com/ohgiraffers/webrpg/user/application/dto/loginDTO.java
- src/main/java/com/ohgiraffers/webrpg/user/application/service/UserApplicationService.java
- src/main/resources/static/index.html
- src/main/resources/templates/main/loginPage.html
- src/main/resources/templates/main/menu.html
---
* #51 
---
---
* gradle settings에서 패키지 이름 체크 필요
---
---
* 기능별 패키지 분리한 구조와 resources 패키지 구조가 다르기 때문에 html에서 location.href를 정의할 때 서버의 route 로 설정하고 해당 route에서 return string의 html resource 경로를 포워딩해야 합니다.
---
---
* ❗️스크린샷 참고 필수
---
---
* 없음
> [#51] 유저 컨트롤러 로그인 구현

- src/main/java/com/ohgiraffers/webrpg/user/application/controller/UserController.java
---
userinfo 기능 구현
---
---
*
---
login에서 생성된 session에 저장된 username을 사용하여 userinfo기능 생성
---
*
---
---
*
---
---
> userController userinfo기능 추가

- src/main/java/com/ohgiraffers/webrpg/hunt/application/dto/GetElementalDTO.java
- src/main/java/com/ohgiraffers/webrpg/hunt/domain/service/HuntExtraElemental.java
- src/main/java/com/ohgiraffers/webrpg/hunt/infra/service/CalcExtraService.java
- src/test/java/com/ohgiraffers/webrpg/hunt/application/service/CompareElementalTests.java
- src/test/java/com/ohgiraffers/webrpg/hunt/application/service/RandomMonsterServiceTests.java
랜덤몬스터 테스트명 수정,
ElementalDTO 타입 수정,
HuntExtraElemental 메소드 내 변수 타입 수정
---
* 속성값 비교에서 오류가 발견되어 수정
---
---
* 제대로 된 비교가 안되어 타입 수정
---
---
*
---
---
*
---
---
> 속성값에 따른 공격력 비율 테스트,

- src/main/java/com/ohgiraffers/webrpg/database/UserInMemoryDatabase.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/application/controller/Controller.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/application/controller/UpgradeController.java
- src/main/java/com/ohgiraffers/webrpg/user/application/controller/UserController.java
- src/main/resources/templates/main/menu.html
- src/main/resources/templates/upgrade/upgrade.html
- src/main/resources/templates/upgrade/upgradeResult.html
---
* #51 
---
---
* 없음
---
---
* upgradeApplicationService 메소드를 통해 받은 데이터를 model Attribute 에 추가
* 조건 불 만족 시, redirect
---
---
* 현재 CSS는 적용이 안된 상태입니다.
---
---
* 없음
> [#51] UpgradeController 및 thymeleaf 적용

- src/main/java/com/ohgiraffers/webrpg/main/controller/MainController.java
- src/main/java/com/ohgiraffers/webrpg/user/application/controller/UserController.java
- src/main/resources/static/index.html
- src/main/resources/templates/hunt/huntSelectMap.html
- src/main/resources/templates/main/loginPage.html
- src/main/resources/templates/main/menu.html
- src/main/resources/templates/upgrade/upgrade.html
- src/main/resources/templates/user/type.html
---
* #75 
---
---
* huntSelectMap 부분이 아직 구현이 되지 않았습니다..
---
---
* user 컨트롤러에 있던 menu, login 를 main 컨트롤러로 분리하였습니다
---
---
* 없음
---
---
* 없음
> [#75] 메인 컨트롤러 구현

- src/main/java/com/ohgiraffers/webrpg/hunt/application/service/HuntElementalDamage.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/service/UserAttackApplicationService.java
- src/test/java/com/ohgiraffers/webrpg/hunt/application/service/CompareElementalTests.java
- src/test/java/com/ohgiraffers/webrpg/hunt/application/service/UserAttackApplicationServiceTests.java
---
* 변경 이유를 작성한다.
* 변경 이유를 작성한다.
---
---
*
---
---
*
---
---
*
---
---
> User Attack service 수정 이후 test 수정

- src/main/java/com/ohgiraffers/webrpg/user/application/controller/UserController.java
- src/main/resources/static/css/hunt.css
- src/main/resources/static/css/upgrade.css
- src/main/resources/static/index.css
- src/main/resources/templates/hunt/huntSelectMap.html
- src/main/resources/templates/hunt/huntmaps/hunt1.html
- src/main/resources/templates/hunt/huntmaps/hunt10.html
- src/main/resources/templates/hunt/huntmaps/hunt2.html
- src/main/resources/templates/hunt/huntmaps/hunt3.html
- src/main/resources/templates/hunt/huntmaps/hunt4.html
- src/main/resources/templates/hunt/huntmaps/hunt5.html
- src/main/resources/templates/hunt/huntmaps/hunt6.html
- src/main/resources/templates/hunt/huntmaps/hunt7.html
- src/main/resources/templates/hunt/huntmaps/hunt8.html
- src/main/resources/templates/hunt/huntmaps/hunt9.html
- src/main/resources/templates/upgrade/upgradeResult.html
- src/main/resources/templates/user/type.html
---
spring boot로 바꾸면서 css나 js ,페이지 이동간의 주소 값이 바뀌면서 
주소값 수정
---
---
* 없음
---
---
*
---
---
*
---
---
> html주소값 수정

- src/main/java/com/ohgiraffers/webrpg/common/interceptor/LoginInterceptor.java
- src/main/java/com/ohgiraffers/webrpg/configuration/WebConfiguration.java
- src/main/java/com/ohgiraffers/webrpg/user/application/controller/UserController.java
---
* #86 
---
---
* session 에 사용자 sequence 없을 경우, 로그인 페이지로 리다이렉트
---
---
* 인터셉터 구현 참고
---
---
* 추후 서블릿 필터 영역으로 이동 필요
---
---
> [#86] 사용자 로그인 예외 처리

- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/HuntIntegratedController.java
---
* 변경 이유를 작성한다.
* 변경 이유를 작성한다.
---
---
*
---
---
*
---
---
*
---
---
> IntegratedHuntController

- src/main/java/com/ohgiraffers/webrpg/hunt/application/dto/MonsterInfoDTO.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/service/MonsterApplicationService.java
- src/test/java/com/ohgiraffers/webrpg/hunt/application/service/MonsterApplicationServiceTests.java
---
* hunt 작업 간에 Monster의 정보를 담을 DTO가 필요하여 제작하였음
* 그에 따라 DTO에 정보를 담을 메소드와 클래스를 제작
---
---
*
---
---
*
---
---
*
---
---
> MonsterApplicationService 제작 및 MonsterInfo 개발

- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/ChoiceMapController.java
- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/HuntIntegratedController.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/vo/Money.java
- src/main/resources/templates/hunt/huntResult.html
- src/main/resources/templates/hunt/huntfail.html
- src/main/resources/templates/hunt/huntmaps/hunt1.html
---
* #97 
---
---
* 전투에 필요한 DTO 데이터 이동 수정
---
---
* 전투에 필요한 DTO를 세션으로 처리하였습니다.
---
---
* 없음
---
---
* 없음
> attackbutton 데이터 처리 완료

- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/HuntIntegratedController.java
- src/main/resources/templates/hunt/huntResult.html
- src/main/resources/templates/hunt/huntmaps/hunt1.html
* 사냥 로직 변경과 웹 연동 및 결과보상 화면 출력
---
---
> HuntResult Test

- src/main/java/com/ohgiraffers/webrpg/user/application/controller/UserController.java
- src/main/resources/templates/main/menu.html
---
* #106
---
---
* 로그아웃 구현
---
---
* 세션에서 removeAttribute를 통해 사용자 sequence를 제거
* redirect 를 `/login`으로 리라이렉트함
---
---
* 없음
---
---
* 없음
> [#106] 로그아웃 간단 구현

- src/main/java/com/ohgiraffers/webrpg/hunt/application/controller/HuntIntegratedController.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/application/controller/UpgradeController.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/application/service/UpgradeApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/domain/service/RequestService.java
- src/main/java/com/ohgiraffers/webrpg/upgrade/infra/service/UserRequestService.java
- src/main/java/com/ohgiraffers/webrpg/user/application/service/UserApplicationService.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/aggregate/enumtype/MoneyMark.java
- src/main/java/com/ohgiraffers/webrpg/user/domain/service/UserDomainService.java
- src/test/java/com/ohgiraffers/webrpg/upgrade/application/controller/UpgradeApplicationServiceTests.java
- src/test/java/com/ohgiraffers/webrpg/user/application/service/UserApplicationServiceTests.java
---
* #105 
---
---
* 돈을 저장하는 메소드와 돈을 사용하는 메소드가 하나로 있던 문제 해결
* 사용하는 경우 SpendMoney 메소드
* 돈을 버는 경우 SaveMoney 메소드
* 구현
---
---
* 돈과 관련된 메소드가 2개가 되었습니다.
---
---
* 없음
---
---
* 관련 이미지 참조
> [#105] 강화 비용 저장 관련 이슈 해결

- src/main/resources/static/css/hunt.css
---
* 사냥 결과 죽었을 때 화면의 버튼 마우스포인터 변경완료
---
> [Html&css] mouse pointer settings hunt result:fail page

- src/main/java/com/ohgiraffers/webrpg/database/MonsterDB.java
---
* 변경 이유를 작성한다.
* 변경 이유를 작성한다.
---
---
*
---
---
*
---
---
*
---
---
> 몬스터 밸런스 패치

- src/main/java/com/ohgiraffers/webrpg/database/MonsterDB.java
---
* 변경 이유를 작성한다.
* 변경 이유를 작성한다.
---
---
*
---
---
*
---
---
*
---
---
> 몬스터DB 수치 수정
